### ISSUE TITLE
Feature Suggestion: autodetect download directories

### ISSUE THREAD

**Issue by aquifolly** [Bijman/srb2dl#2]
auto-detection of `.srb2`,`.srb2kart` or equivalent directories in the home folder, and ask which folder(s) to which to download the files

**Comment by Bijman** [comment]
Implemented this feature in commit c79e4b6. To activate it, you need to add `export SRB2DLAUTODIR=1` in shell configuration file. Keep in mind that, parsing download path argument to script is disabled, when this variable is set.
