### ISSUE TITLE
[Suggestion] Show history

### ISSUE THREAD

**Issue by aquifolly** [Bijman/srb2dl#3]
example: [Willo](https://mb.srb2.org/addons/willo-the-cat.3457/) has two versions, being [1](https://mb.srb2.org/addons/willo-the-cat.3457/version/5117/download) and [1.1](https://mb.srb2.org/addons/willo-the-cat.3457/version/6257/download) and srb2dl (as far as I know) doesn't have an option for displaying [history](https://mb.srb2.org/addons/willo-the-cat.3457/history).

**Comment by Bijman** [comment]
Added this feature to commit a5bedb8 . To run it, enter `srb2dl --history [MB.SRB2.ORG ADDON ID]`.

**Comment by Bijman** [comment]
You can also download version when selecting addon as usual as there is entry called "History" in the file selection.
