### ISSUE TITLE
Resource list doesn't alway match what's shown if more than 20 resources

### ISSUE THREAD

**Issue by SteelT1** [Bijman/srb2dl#9]
For example, picking the custom gametype category then picking option 20 prompts if L_FreezeTag_v4.lua (as of this writing) should be downloaded, instead of ZRs_RingSlingerNEO-v3.pk3, option 21 goes to the next page, and option 22 goes to the previous page.

**Comment by aquifolly** [comment]
maybe something like `prev`, `next`, `back` instead of the numbers?

**Comment by Bijman** [comment]
Most likely the cause of issue is that new label "Open Assets", which was introduced in SRB2 Addons section of SRB2 MB, does not align with title of addon and it goes to the next line. This messes up number of entries, which is visible by user vs links selected "behind the scenes".

**Comment by Bijman** [comment]
Fixed this in commit a5bedb8. Issue was due to not aligning correctly label "Open Assets" with addon's name, which caused multiple entries having incorrect links to addons.
